[project]
name = "complex-systems"
version = "0.1.0"
description = "Cellular Automata based on river flows."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.2",
    "torch>=2.5.1",
]
