[project]
name = "complex-systems"
version = "0.1.0"
description = "Cellular Automata based on river flows."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ffmpeg>=1.4",
    "matplotlib>=3.10.0",
    "numpy>=2.2.2",
    "pyqt6>=6.8.0",
    "torch>=2.5.1",
]
